[package]
name = "latte-work-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
[features]
custom-protocol = ["tauri/custom-protocol"]
[build-dependencies]
cc = "1"
tauri-build = { version = "2", features = [] }
[dependencies]
anyhow.workspace = true
latte-work-config.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
latte-work-protocol.workspace = true
latte-work-client.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
[lints]
workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["std", "NSPasteboard", "NSPasteboardItem"] }
objc2-foundation = { version = "0.3.2", default-features = false, features = ["std", "NSString", "NSURL"] }
