[package]
name = "latte-work-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
[dependencies]
latte-work-protocol.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
url = "2"
tempfile = "3"
reqwest = { version = "0.13", default-features = false, features = ["blocking", "rustls"] }
[lints]
workspace = true
