// Generated by make types. Do not edit.

export type JsonValue =
  | number
  | string
  | boolean
  | Array<JsonValue>
  | { [key in string]?: JsonValue }
  | null;
export type Project = { id: string; name: string; path: string };
export type TerminalInfo = {
  id: string;
  project_id: string;
  title: string;
  exited: boolean;
  exit_code: number | null;
};
export type Status =
  | "ready"
  | "running"
  | "waiting"
  | "completed"
  | "failed"
  | "stopped"
  | "unknown";
export type Effort = "low" | "medium" | "high" | "xhigh" | "max";
export type Session = {
  id: string;
  project_id: string;
  title: string;
  agent: string;
  native_id: string | null;
  model: string | null;
  effort: Effort | null;
  status: Status;
  created_at: number;
  custom_title: boolean;
  pinned_at: number | null;
  unread: boolean;
  archived: boolean;
};
export type EventKind =
  | { kind: "user"; text: string; request_id: string }
  | { kind: "text"; text: string }
  | { kind: "tool"; id: string; name: string; input: JsonValue }
  | { kind: "tool_result"; id: string; content: JsonValue; is_error: boolean }
  | { kind: "approval"; request_id: string; tool: string; input: JsonValue }
  | { kind: "approval_resolved"; request_id: string; allow: boolean }
  | { kind: "state"; status: Status; message: string | null }
  | { kind: "notice"; text: string };
export type Event = {
  seq: number;
  session_id: string;
  at: number;
  event: EventKind;
};
export type FileEntry = { name: string; path: string; directory: boolean };
export type AgentInfo = {
  id: string;
  name: string;
  available: boolean;
  provider_protocols: Array<ProviderProtocol>;
  detail: string;
};
export type ProviderProtocol =
  "anthropic_messages" | "openai_chat" | "openai_responses";
export type ProviderAuth = "bearer" | "api_key";
export type Provider = {
  id: string;
  name: string;
  protocol: ProviderProtocol;
  base_url: string;
  model: string;
  models: Array<string>;
  auth: ProviderAuth;
  has_credential: boolean;
  revision: string;
};
export type ProviderDraft = {
  id: string | null;
  name: string;
  protocol: ProviderProtocol;
  base_url: string;
  model: string;
  models: Array<string>;
  auth: ProviderAuth;
  /**
   * None preserves a saved credential; plaintext is write-only over the private host transport.
   */
  credential: string | null;
};
export type ProviderTarget = { ssh: string; server_path: string };
export type AgentProviderBinding = {
  agent: string;
  provider_id: string;
  provider_revision: string;
};
export type ProviderSnapshot = { provider: Provider; credential: string };
export type Request =
  | { method: "hello"; version: number }
  | { method: "projects" }
  | { method: "terminals"; project_id: string }
  | {
      method: "create_terminal";
      project_id: string;
      terminal_id: string;
      cols: number;
      rows: number;
    }
  | { method: "read_terminal"; terminal_id: string; after: number }
  | { method: "write_terminal"; terminal_id: string; data: Array<number> }
  | {
      method: "resize_terminal";
      terminal_id: string;
      cols: number;
      rows: number;
    }
  | { method: "close_terminal"; terminal_id: string }
  | { method: "providers" }
  | {
      method: "models";
      agent: string;
      model: string | null;
      project_id: string | null;
    }
  | { method: "save_provider"; provider: ProviderDraft }
  | { method: "delete_provider"; id: string }
  | {
      method: "bind_agent_provider";
      agent: string;
      provider_id: string | null;
      target: ProviderTarget | null;
    }
  | {
      method: "sync_agent_provider";
      agent: string;
      snapshot: ProviderSnapshot | null;
    }
  | { method: "add_project"; path: string; name: string | null }
  | { method: "rename_project"; project_id: string; name: string }
  | { method: "remove_project"; project_id: string }
  | { method: "browse_directories"; path: string | null }
  | { method: "sessions"; project_id: string }
  | { method: "pinned_sessions" }
  | { method: "rename_session"; session_id: string; title: string }
  | { method: "pin_session"; session_id: string; pinned: boolean }
  | { method: "mark_session_unread"; session_id: string; unread: boolean }
  | { method: "archive_session"; session_id: string; archived: boolean }
  | { method: "create_session"; project_id: string; agent: string }
  | {
      method: "send";
      session_id: string;
      request_id: string;
      text: string;
      model: string | null;
      effort: Effort | null;
    }
  | { method: "poll"; session_id: string; after: number }
  | {
      method: "approve";
      session_id: string;
      request_id: string;
      allow: boolean;
    }
  | { method: "cancel"; session_id: string }
  | { method: "files"; project_id: string; path: string }
  | { method: "read_file"; project_id: string; path: string }
  | { method: "diff"; project_id: string };
export type Response =
  | { kind: "terminals"; terminals: Array<TerminalInfo> }
  | { kind: "terminal"; terminal: TerminalInfo }
  | {
      kind: "terminal_output";
      terminal: TerminalInfo;
      data: Array<number>;
      next: number;
      has_more: boolean;
      truncated: boolean;
    }
  | {
      kind: "models";
      models: Array<string>;
      provider: string | null;
      default_model: string | null;
      effort_levels: Array<Effort>;
      /**
       * Display metadata only; keys remain the original selectable model IDs.
       */
      model_labels: { [key in string]?: string };
    }
  | {
      kind: "providers";
      providers: Array<Provider>;
      bindings: Array<AgentProviderBinding>;
    }
  | {
      kind: "hello";
      version: number;
      server_id: string;
      agents: Array<AgentInfo>;
    }
  | { kind: "projects"; projects: Array<Project> }
  | { kind: "project"; project: Project }
  | { kind: "sessions"; sessions: Array<Session> }
  | { kind: "session"; session: Session }
  | { kind: "accepted"; duplicate: boolean }
  | {
      kind: "events";
      events: Array<Event>;
      session: Session;
      has_more: boolean;
    }
  | { kind: "files"; entries: Array<FileEntry> }
  | {
      kind: "directories";
      path: string;
      parent: string | null;
      entries: Array<FileEntry>;
      truncated: boolean;
    }
  | { kind: "content"; text: string; truncated: boolean }
  | { kind: "ok" }
  | { kind: "error"; code: string; message: string };
